-- 코드를 입력하세요
SELECT B.ANIMAL_ID
      ,B.NAME
  FROM ANIMAL_INS A RIGHT JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
 WHERE A.ANIMAL_ID IS NULL
ORDER BY 1 ASC

-- 조인 안쓰고도 가능한거
SELECT ANIMAL_ID
      ,NAME
  FROM ANIMAL_OUTS 
 WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID
                           FROM ANIMAL_INS)
ORDER BY 1 ASC
