-- 코드를 입력하세요
SELECT B.AUTHOR_ID         AS AUTHOR_ID
      ,B.AUTHOR_NAME       AS AUTHOR_NAME
      ,A.CATEGORY          AS CATEGORY
      ,SUM(A.PRICE * C.SALES) AS TOTAL_SALES
  FROM BOOK A, AUTHOR B, BOOK_SALES C
 WHERE A.BOOK_ID = C.BOOK_ID
   AND A.AUTHOR_ID = B.AUTHOR_ID
   AND TO_CHAR(C.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY
ORDER BY 1, 3 DESC